// Authentication
export const SET_TOKEN = 'SET_TOKEN'
export const REMOVE_TOKEN = 'REMOVE_TOKEN'

// Workout
export const ADD_WORKOUT = 'ADD_WORKOUT'
export const REMOVE_WORKOUT = 'REMOVE_WORKOUT'
export const UPDATE_WORKOUT = 'UPDATE_WORKOUT'
export const SET_WORKOUTS = 'SET_WORKOUTS'
export const ADD_SET_TO_WORKOUT = 'ADD_SET_TO_WORKOUT'
export const ADD_EXERCISE_TO_WORKOUT = 'ADD_EXERCISE_TO_WORKOUT'
export const CHANGE_WORKOUT_DETAILS = 'CHANGE_WORKOUT_DETAILS'
export const CHANGE_EXERCISES = 'CHANGE_EXERCISES'

export const SET_ACTIVE_WORKOUT = 'SET_ACTIVE_WORKOUT'
export const CLEAR_ACTIVE_WORKOUT = 'CLEAR_ACTIVE_WORKOUT'

// exercises
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const SET_EXERCISES = 'SET_EXERCISES'
