// Authentication
export const SET_TOKEN = 'SET_TOKEN'
export const REMOVE_TOKEN = 'REMOVE_TOKEN'

// Workout
export const ADD_WORKOUT = 'ADD_WORKOUT'
export const REMOVE_WORKOUT = 'REMOVE_WORKOUT'
export const UPDATE_WORKOUT = 'UPDATE_WORKOUT'
export const SET_WORKOUTS = 'SET_WORKOUTS'

export const ADD_SET_TO_ENTRY = 'ADD_SET_TO_ENTRY'
export const ADD_ENTRY_TO_WORKOUT = 'ADD_ENTRY_TO_WORKOUT'
export const REMOVE_SET_FROM_ENTRY = 'REMOVE_SET_FROM_ENTRY'

export const CHANGE_EXERCISE = 'CHANGE_EXERCISE'
export const CHANGE_SET_DETAILS = 'CHANGE_SET_DETAILS'
export const CHANGE_WORKOUT_DETAILS = 'CHANGE_WORKOUT_DETAILS'

export const SET_ACTIVE_WORKOUT = 'SET_ACTIVE_WORKOUT'
export const SET_NEW_WORKOUT = 'SET_NEW_WORKOUT'

// exercises
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const SET_EXERCISES = 'SET_EXERCISES'

// messages
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
